name: Build Plugin

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - 'js/dist/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install
        working-directory: js

      - name: Build Plugin
        run: bun run build
        working-directory: js

      - name: Commit & Push Build
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update build [skip ci]"
          branch: dist
          create_branch: true
          file_pattern: js/dist/*
